About/urls.py
from django.urls import path, include
from .views import (
    about,

)

app_name = 'About'

urlpatterns = [
    # Main pages
    path('about/', about, name='about'),

]

Contact/urls.py
from django.urls import path, include
from .views import (
    contact_view
)

app_name = 'Contact'

urlpatterns = [
    # Contact
    path('contact/', contact_view, name='contact'),
]

Resume/urls.py
from django.urls import path, include
from .views import (
    resume,
)

app_name = 'Resume'

urlpatterns = [
    # Main pages
    path('resume/', resume, name='resume'),

]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('root.urls')),
    path('' , include('About.urls')),
    path('' , include('Contact.urls')),
    path('' , include('Service.urls')),
    path('', include('Resume.urls')),
    path('captcha/', include('captcha.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

root/urls.py
from django.urls import path, include
from .views import (
    home,
    signup,
    login_view, logout_view,
    password_reset_request,
    password_reset_code,
    password_change,
    change, change_profile_icon,
    save_profile_changes
)

app_name = 'root'

urlpatterns = [
    # Main pages
    path('', home, name='home'),
    
    # Authentication
    path('signup/', signup, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
    # Password management
    path('password_reset/', password_reset_request, name='password_reset_request'),
    path('password_reset_code/', password_reset_code, name='password_reset_code'),
    path('password_change/', password_change, name='password_change'),
    
    # Profile management
    path('Change/', change, name='Change'),
    path('change-icon/', change_profile_icon, name='change_profile_icon'),
    path('save_profile_changes/', save_profile_changes, name='save_profile_changes'),
    
    # Third-party apps
    path('captcha/', include('captcha.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>AMIRMAHDI</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Personal
  * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="index-page">

  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

      <a href="{% url 'root:home' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="{% static 'assets/img/logo.png' %}" alt=""> -->
        <h1 class="sitename">Home</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'root:home' %}" class="{% if active_page == 'home' %}active{% endif %}">Home</a></li>
          <li><a href="{% url 'About:about' %}" class="{% if active_page == 'about' %}active{% endif %}">About</a></li>
          <li><a href="{% url 'Resume:resume' %}" class="{% if active_page == 'resume' %}active{% endif %}">Resume</a></li>
          <li><a href="{% url 'Services:services' %}" class="{% if active_page == 'services' %}active{% endif %}">Projects</a></li>
          <li><a href="{% url 'Contact:contact' %}" class="{% if active_page == 'contact' %}active{% endif %}">Contact</a></li>

          
          {% if user.is_authenticated %}
            <!-- If user is logged in, show username and logout button -->
            <a href="{% url 'root:Change' %}" class="nav-link text-center">
                   <span>( welcome to، {{ user.first_name}} )</span>
          </a>
          

          <span class="separator">ㅤ</span>
              <a href="{% url 'root:logout' %}" class="btn btn-secondary">logout</a>
            </li>
          {% else %}
            <!-- If user is not logged in, show login and signup buttons -->
            <li>
              <a href="{% url 'root:login' %}" class="btn btn-primary me-2">login</a>
            </li>
            <span class="separator">///</span>
            <li>
              <a href="{% url 'root:signup' %}" class="btn btn-secondary">signup</a>
            </li>
          {% endif %}
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>

    </div>
  </header>
{% block 'content' %}


{% endblock 'content' %}


  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center">
    <i class="bi bi-arrow-up-short"></i>
  </a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/typed.js/typed.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  
</body>

</html>